import { z } from "zod";

export const zTranscriptProvider = z.enum(["youtube", "azure-whisper"]);
export type TranscriptProvider = z.infer<typeof zTranscriptProvider>;

export const zTranscriptStatus = z.enum([
  "pending",
  "ready",
  "unavailable",
  "failed",
]);
export type TranscriptStatus = z.infer<typeof zTranscriptStatus>;

export const zTranscriptAttachmentsStatus = z.enum([
  "pending",
  "ready",
  "partial",
  "failed",
]);
export type TranscriptAttachmentsStatus = z.infer<
  typeof zTranscriptAttachmentsStatus
>;

export const zSummaryProvenance = z.enum(["web", "transcript", "manual"]);
export type SummaryProvenance = z.infer<typeof zSummaryProvenance>;

export const zTranscriptSchema = z.object({
  id: z.string(),
  bookmarkId: z.string(),
  createdAt: z.date(),
  provider: zTranscriptProvider,
  providerItemId: z.string(),
  status: zTranscriptStatus,
  statusMessage: z.string().nullish(),
  sourceAttachmentsStatus: zTranscriptAttachmentsStatus,
  selectedTrackId: z.string().nullish(),
  sourceLanguage: z.string().nullish(),
  sourceIsAutoGenerated: z.boolean().nullish(),
  sourceTranscript: z.string().nullish(),
  text: z.string().nullish(),
  manualOverride: z.boolean(),
  revision: z.number().int().nonnegative(),
  sourceFingerprint: z.string().nullish(),
  sourceFetchedAt: z.date().nullish(),
  modifiedAt: z.date().nullish(),
});
export type ZTranscript = z.infer<typeof zTranscriptSchema>;

export const zTranscriptAssetSchema = z.object({
  id: z.string(),
  assetType: z.literal("captionSource"),
  fileName: z.string().nullish(),
});

export const zTranscriptResponseSchema = zTranscriptSchema.extend({
  sourceAttachments: z.array(zTranscriptAssetSchema),
});
export type ZTranscriptResponse = z.infer<typeof zTranscriptResponseSchema>;

export const zUpdateTranscriptRequestSchema = z.object({
  bookmarkId: z.string(),
  text: z.string(),
  expectedRevision: z.number().int().nonnegative().optional(),
});

export const zResetTranscriptRequestSchema = z.object({
  bookmarkId: z.string(),
});

export const zRetryTranscriptRequestSchema = z.object({
  bookmarkId: z.string(),
});
