import crypto from "crypto";
import fs from "fs";
import * as os from "os";
import path from "path";
import { execa } from "execa";
import { and, eq, inArray } from "drizzle-orm";
import { workerStatsCounter } from "metrics";
import { withWorkerEventLog, withWorkerTracing } from "workerTracing";

import {
  assets,
  AssetTypes,
  bookmarkTranscripts,
  bookmarks,
  users,
} from "@karakeep/db/schema";
import { db } from "@karakeep/db";
import {
  addLogFields,
  EmbeddingsQueue,
  OpenAIQueue,
  QueuePriority,
  QuotaService,
  SearchIndexingQueue,
  TranscriptQueue,
  ZTranscriptRequest,
  zTranscriptRequestSchema,
} from "@karakeep/shared-server";
import {
  DequeuedJob,
  EnqueueOptions,
  getQueueClient,
} from "@karakeep/shared/queueing";
import {
  getProxyAgent,
  resolveValidatedRedirectUrl,
  selectRunProxies,
} from "network";
import serverConfig from "@karakeep/shared/config";
import {
  newAssetId,
  saveAssetFromFile,
  silentDeleteAsset,
} from "@karakeep/shared/assetdb";
import {
  getYouTubeVideoId,
  normalizeSubtitleText,
  subtitleContentType,
} from "@karakeep/shared/youtube";
import logger from "@karakeep/shared/logger";
import { transcribeAsset, transcribeRemoteUrl } from "./mediaTranscription";

const TRANSCRIPT_TMP_FOLDER = path.join(os.tmpdir(), "transcript_downloads");
const MAX_CAPTION_FILES = 50;
const MAX_CAPTION_BYTES = 20 * 1024 * 1024;

interface CaptionArtifact {
  fileName: string;
  contentType: string;
  language: string | null;
  isAutoGenerated: boolean;
  bytes: Buffer;
}

function parseCaptionMetadata(fileName: string, videoId: string) {
  const stem = path.basename(fileName, path.extname(fileName));
  const prefix = `${videoId}.`;
  const suffix = stem.startsWith(prefix) ? stem.slice(prefix.length) : stem;
  const parts = suffix.split(".");
  const sourceKind = parts[0]?.toLowerCase();
  const hasSourceKind = sourceKind === "manual" || sourceKind === "auto";
  const language = parts[hasSourceKind ? 1 : 0] ?? null;
  const variantParts = parts.slice(hasSourceKind ? 2 : 1);
  const variant = variantParts.join(".");

  return {
    language,
    isAutoGenerated:
      sourceKind === "auto" || /(?:auto|automatic|asr)/i.test(variant),
  };
}

function languageMatches(language: string | null, requested: string | null) {
  if (!language || !requested) return false;
  const normalizedLanguage = language.toLowerCase();
  const normalizedRequested = requested.toLowerCase();
  return (
    normalizedLanguage === normalizedRequested ||
    normalizedLanguage.split("-")[0] === normalizedRequested.split("-")[0]
  );
}

function selectCaptionArtifact(
  artifacts: CaptionArtifact[],
  preferredLanguage: string | null,
) {
  return [...artifacts].sort((a, b) => {
    const preferredRank = (artifact: CaptionArtifact) =>
      languageMatches(artifact.language, preferredLanguage)
        ? 0
        : artifact.language?.toLowerCase().startsWith("en")
          ? 1
          : 2;
    const languageRank = preferredRank(a) - preferredRank(b);
    if (languageRank !== 0) return languageRank;
    if (a.isAutoGenerated !== b.isAutoGenerated) {
      return a.isAutoGenerated ? 1 : -1;
    }
    const formatRank = (artifact: CaptionArtifact) => {
      switch (path.extname(artifact.fileName).toLowerCase()) {
        case ".vtt":
          return 0;
        case ".srt":
          return 1;
        case ".ttml":
        case ".dfxp":
          return 2;
        case ".ass":
        case ".ssa":
          return 3;
        case ".lrc":
        case ".srv3":
          return 4;
        case ".json3":
          return 5;
        default:
          return 6;
      }
    };
    const formatDifference = formatRank(a) - formatRank(b);
    if (formatDifference !== 0) return formatDifference;
    return a.fileName.localeCompare(b.fileName);
  })[0];
}

async function listCaptionArtifacts(
  directory: string,
  videoId: string,
): Promise<CaptionArtifact[]> {
  const entries = await fs.promises.readdir(directory, { withFileTypes: true });
  const artifacts: CaptionArtifact[] = [];
  let totalBytes = 0;

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isFile() || entry.name.endsWith(".part")) continue;
    const filePath = path.join(directory, entry.name);
    const bytes = await fs.promises.readFile(filePath);
    if (bytes.length === 0) continue;
    if (artifacts.length >= MAX_CAPTION_FILES) break;
    if (totalBytes + bytes.length > MAX_CAPTION_BYTES) break;

    const metadata = parseCaptionMetadata(entry.name, videoId);
    artifacts.push({
      fileName: entry.name,
      contentType: subtitleContentType(entry.name),
      language: metadata.language,
      isAutoGenerated: metadata.isAutoGenerated,
      bytes,
    });
    totalBytes += bytes.length;
  }

  return artifacts;
}

function fingerprintArtifact(artifact: CaptionArtifact) {
  return crypto
    .createHash("sha256")
    .update(artifact.fileName)
    .update(artifact.bytes)
    .digest("hex");
}

async function deleteOldCaptionAssets(userId: string, assetIds: string[]) {
  await Promise.all(
    assetIds.map((assetId) => silentDeleteAsset(userId, assetId)),
  );
}

async function clearPendingSummaryIfEmpty(bookmark: {
  id: string;
  summary: string | null;
  summarizationStatus: "pending" | "failure" | "success" | null;
}) {
  if (!bookmark.summary && bookmark.summarizationStatus === "pending") {
    await db
      .update(bookmarks)
      .set({ summarizationStatus: null })
      .where(eq(bookmarks.id, bookmark.id));
  }
}

interface TranscriptBookmark {
  id: string;
  userId: string;
  summary: string | null;
  summarizationStatus: "pending" | "failure" | "success" | null;
}

function fingerprintTranscript(
  provider: string,
  providerItemId: string,
  text: string,
) {
  const transcriptionModel = serverConfig.transcription.azureSpeech.model;

  return crypto
    .createHash("sha256")
    .update(provider)
    .update(providerItemId)
    .update(transcriptionModel)
    .update(text)
    .digest("hex");
}

async function saveGeneratedTranscript({
  bookmark,
  provider,
  providerItemId,
  sourceTranscript,
  sourceLanguage,
  selectedTrackId,
  sourceFingerprint,
  shouldSummarize,
}: {
  bookmark: TranscriptBookmark;
  provider: "youtube" | "azure-speech";
  providerItemId: string;
  sourceTranscript: string;
  sourceLanguage?: string;
  selectedTrackId: string;
  sourceFingerprint: string;
  shouldSummarize: boolean;
}) {
  const existing = await db.query.bookmarkTranscripts.findFirst({
    where: and(
      eq(bookmarkTranscripts.bookmarkId, bookmark.id),
      eq(bookmarkTranscripts.provider, provider),
    ),
  });
  const sourceChanged = existing?.sourceFingerprint !== sourceFingerprint;
  const manualOverride = existing?.manualOverride ?? false;
  const nextRevision = sourceChanged
    ? (existing?.revision ?? 0) + (manualOverride ? 0 : 1)
    : (existing?.revision ?? 0);

  await db.transaction(async (tx) => {
    const transcript = await tx.query.bookmarkTranscripts.findFirst({
      where: and(
        eq(bookmarkTranscripts.bookmarkId, bookmark.id),
        eq(bookmarkTranscripts.provider, provider),
      ),
    });
    if (!transcript) {
      throw new Error("Transcript row disappeared during processing");
    }

    await tx
      .update(bookmarkTranscripts)
      .set({
        providerItemId,
        status: "ready",
        statusMessage: null,
        sourceAttachmentsStatus: "ready",
        selectedTrackId,
        sourceLanguage: sourceLanguage ?? null,
        sourceIsAutoGenerated: true,
        sourceTranscript,
        text: manualOverride ? transcript.text : sourceTranscript,
        manualOverride,
        revision: nextRevision,
        sourceFingerprint,
        sourceFetchedAt: new Date(),
        modifiedAt: new Date(),
      })
      .where(eq(bookmarkTranscripts.id, transcript.id));

    if (sourceChanged && !manualOverride) {
      const bookmarkRow = await tx.query.bookmarks.findFirst({
        where: eq(bookmarks.id, bookmark.id),
        columns: { summaryProvenance: true },
      });
      if (bookmarkRow?.summaryProvenance !== "manual") {
        await tx
          .update(bookmarks)
          .set({
            summaryProvenance: "transcript",
            summaryStale: true,
            summarizationStatus: shouldSummarize ? "pending" : null,
            modifiedAt: new Date(),
          })
          .where(eq(bookmarks.id, bookmark.id));
      }
    }
  });

  return { sourceChanged, manualOverride, nextRevision };
}

async function enqueueTranscriptEnrichment(
  bookmark: TranscriptBookmark,
  job: DequeuedJob<ZTranscriptRequest>,
) {
  const idempotencyPrefix = `transcript:${job.id}`;
  const enqueueOpts: EnqueueOptions = {
    priority: job.priority ?? QueuePriority.Default,
    groupId: bookmark.userId,
  };
  if (serverConfig.embedding.enableAutoIndexing) {
    await EmbeddingsQueue.enqueue(
      {
        bookmarkId: bookmark.id,
        type: "embed",
        runTaggingOnComplete: true,
      },
      { ...enqueueOpts, idempotencyKey: `${idempotencyPrefix}:embed` },
    );
  } else {
    await OpenAIQueue.enqueue(
      { bookmarkId: bookmark.id, type: "tag" },
      { ...enqueueOpts, idempotencyKey: `${idempotencyPrefix}:tag` },
    );
  }
}

async function enqueueTranscriptSummary(
  bookmark: TranscriptBookmark,
  job: DequeuedJob<ZTranscriptRequest>,
  revision: number,
) {
  if (!serverConfig.inference.enableAutoSummarization) {
    return;
  }
  await OpenAIQueue.enqueue(
    {
      bookmarkId: bookmark.id,
      type: "summarize",
      summarySource: "transcript",
      transcriptRevision: revision,
    },
    {
      priority: job.priority ?? QueuePriority.Default,
      groupId: bookmark.userId,
      idempotencyKey: `transcript:${job.id}:summary:${revision}`,
    },
  );
}

async function enqueueRefreshFallbackEnrichment(
  bookmark: { id: string; userId: string },
  jobId: string,
  priority: number | undefined,
  shouldSummarize: boolean,
) {
  const enqueueOpts: EnqueueOptions = {
    priority: priority ?? QueuePriority.Default,
    groupId: bookmark.userId,
  };
  const idempotencyPrefix = `transcript-refresh:${jobId}:fallback`;

  if (serverConfig.embedding.enableAutoIndexing) {
    await EmbeddingsQueue.enqueue(
      {
        bookmarkId: bookmark.id,
        type: "embed",
        runTaggingOnComplete: true,
      },
      { ...enqueueOpts, idempotencyKey: `${idempotencyPrefix}:embed` },
    );
  } else {
    await OpenAIQueue.enqueue(
      { bookmarkId: bookmark.id, type: "tag" },
      { ...enqueueOpts, idempotencyKey: `${idempotencyPrefix}:tag` },
    );
  }

  if (shouldSummarize && serverConfig.inference.enableAutoSummarization) {
    await OpenAIQueue.enqueue(
      {
        bookmarkId: bookmark.id,
        type: "summarize",
        summarySource: "web",
      },
      { ...enqueueOpts, idempotencyKey: `${idempotencyPrefix}:summary` },
    );
  }
}

function isCaptionUnavailableError(error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  return /no subtitles|no automatic captions|subtitles are not available|requested format is not available|does not have subtitles/i.test(
    message,
  );
}

async function downloadCaptionArtifacts(
  url: string,
  videoId: string,
  job: DequeuedJob<ZTranscriptRequest>,
): Promise<CaptionArtifact[]> {
  const runProxy = selectRunProxies();
  const resolvedUrl = await resolveValidatedRedirectUrl(
    url,
    { signal: job.abortSignal },
    runProxy,
  );
  const proxy = getProxyAgent(resolvedUrl.toString(), runProxy);
  await fs.promises.mkdir(TRANSCRIPT_TMP_FOLDER, { recursive: true });
  const directory = await fs.promises.mkdtemp(
    path.join(TRANSCRIPT_TMP_FOLDER, "youtube-"),
  );
  const args = [
    ...serverConfig.crawler.ytDlpArguments,
    "--skip-download",
    "--sub-langs",
    "all",
    "--no-playlist",
    ...(proxy ? ["--proxy", proxy.proxy.toString()] : []),
  ];

  try {
    let firstError: unknown;
    for (const source of ["manual", "auto"] as const) {
      const outputTemplate = path.join(
        directory,
        `${videoId}.${source}.%(language)s.%(format_id)s.%(ext)s`,
      );
      for (const format of [
        "vtt",
        "srt",
        "ttml",
        "ass",
        "lrc",
        "srv1",
        "srv2",
        "srv3",
        "json3",
      ]) {
        try {
          await execa(
            "yt-dlp",
            [
              ...args,
              source === "manual" ? "--write-subs" : "--write-auto-subs",
              source === "manual" ? "--no-write-auto-subs" : "--no-write-subs",
              "--sub-format",
              format,
              "--output",
              outputTemplate,
              resolvedUrl.toString(),
            ],
            { cancelSignal: job.abortSignal },
          );
        } catch (error) {
          firstError ??= error;
        }
      }
    }

    const artifacts = await listCaptionArtifacts(directory, videoId);
    if (
      artifacts.length === 0 &&
      firstError &&
      !isCaptionUnavailableError(firstError)
    ) {
      throw firstError;
    }
    return artifacts;
  } finally {
    await fs.promises.rm(directory, { recursive: true, force: true });
  }
}

interface MediaBookmark extends TranscriptBookmark {
  asset: {
    assetType: string;
    assetId: string;
    fileName: string | null;
  };
}

async function runAssetTranscript(
  bookmark: MediaBookmark,
  job: DequeuedJob<ZTranscriptRequest>,
) {
  if (!serverConfig.transcription.enabled) {
    await clearPendingSummaryIfEmpty(bookmark);
    return;
  }

  const user = await db.query.users.findFirst({
    where: eq(users.id, bookmark.userId),
    columns: { autoSummarizationEnabled: true },
  });
  const shouldSummarize =
    serverConfig.inference.enableAutoSummarization &&
    user?.autoSummarizationEnabled !== false;
  const mediaTranscripts = await db.query.bookmarkTranscripts.findMany({
    where: and(
      eq(bookmarkTranscripts.bookmarkId, bookmark.id),
      inArray(bookmarkTranscripts.provider, ["azure-speech", "azure-whisper"]),
    ),
  });
  const existing =
    mediaTranscripts.find(
      (transcript) => transcript.provider === "azure-speech",
    ) ??
    mediaTranscripts.find(
      (transcript) => transcript.provider === "azure-whisper",
    );

  await db
    .insert(bookmarkTranscripts)
    .values({
      bookmarkId: bookmark.id,
      provider: "azure-speech",
      providerItemId: bookmark.asset.assetId,
      status: "pending",
      sourceAttachmentsStatus: "pending",
      manualOverride: existing?.manualOverride ?? false,
      sourceTranscript: existing?.sourceTranscript ?? null,
      text: existing?.text ?? null,
      revision: existing?.revision ?? 0,
    })
    .onConflictDoUpdate({
      target: [bookmarkTranscripts.bookmarkId, bookmarkTranscripts.provider],
      set: {
        providerItemId: bookmark.asset.assetId,
        status: "pending",
        statusMessage: null,
        sourceAttachmentsStatus: "pending",
      },
    });

  let result;
  try {
    result = await transcribeAsset({
      userId: bookmark.userId,
      assetId: bookmark.asset.assetId,
      fileName: bookmark.asset.fileName,
      abortSignal: job.abortSignal,
    });
  } catch (error) {
    await db
      .update(bookmarkTranscripts)
      .set({
        status: "failed",
        statusMessage: error instanceof Error ? error.message : String(error),
        sourceAttachmentsStatus: existing?.sourceAttachmentsStatus ?? "failed",
      })
      .where(
        and(
          eq(bookmarkTranscripts.bookmarkId, bookmark.id),
          eq(bookmarkTranscripts.provider, "azure-speech"),
        ),
      );
    if (!job.data.forceEnrichment) {
      await clearPendingSummaryIfEmpty(bookmark);
    }
    throw error;
  }

  const sourceFingerprint = fingerprintTranscript(
    "azure-speech",
    bookmark.asset.assetId,
    result.text,
  );
  const saved = await saveGeneratedTranscript({
    bookmark,
    provider: "azure-speech",
    providerItemId: bookmark.asset.assetId,
    sourceTranscript: result.text,
    sourceLanguage: result.language,
    selectedTrackId: "azure-speech",
    sourceFingerprint,
    shouldSummarize,
  });

  if (
    (saved.sourceChanged && !saved.manualOverride) ||
    job.data.forceEnrichment
  ) {
    await enqueueTranscriptEnrichment(bookmark, job);
    if (shouldSummarize) {
      await enqueueTranscriptSummary(bookmark, job, saved.nextRevision);
    }
  }
  await SearchIndexingQueue.enqueue(
    { bookmarkId: bookmark.id, type: "index" },
    {
      priority: job.priority ?? QueuePriority.Default,
      groupId: bookmark.userId,
    },
  );

  addLogFields<"transcriptWorker.run">({
    "bookmark.id": bookmark.id,
    "transcript.provider": "azure-speech",
    "transcript.source_language": result.language,
    "transcript.source_files": 1,
  });
}

async function runTranscript(job: DequeuedJob<ZTranscriptRequest>) {
  const bookmark = await db.query.bookmarks.findFirst({
    where: eq(bookmarks.id, job.data.bookmarkId),
    columns: {
      id: true,
      userId: true,
      type: true,
      summary: true,
      summarizationStatus: true,
    },
    with: {
      link: { columns: { url: true } },
      asset: { columns: { assetType: true, assetId: true, fileName: true } },
    },
  });

  if (!bookmark) {
    return;
  }

  if (
    bookmark.type === "asset" &&
    bookmark.asset &&
    (bookmark.asset.assetType === "video" ||
      bookmark.asset.assetType === "audio")
  ) {
    await runAssetTranscript(bookmark, job);
    return;
  }

  if (!bookmark.link || bookmark.type !== "link") {
    return;
  }

  const videoId = getYouTubeVideoId(bookmark.link.url);
  if (!videoId) {
    await db
      .insert(bookmarkTranscripts)
      .values({
        bookmarkId: bookmark.id,
        provider: "youtube",
        providerItemId: "unknown",
        status: "unavailable",
        statusMessage: "Bookmark URL is not a supported YouTube URL",
        sourceAttachmentsStatus: "ready",
      })
      .onConflictDoNothing();
    await clearPendingSummaryIfEmpty(bookmark);
    return;
  }

  const existing = await db.query.bookmarkTranscripts.findFirst({
    where: and(
      eq(bookmarkTranscripts.bookmarkId, bookmark.id),
      eq(bookmarkTranscripts.provider, "youtube"),
    ),
  });

  await db
    .insert(bookmarkTranscripts)
    .values({
      bookmarkId: bookmark.id,
      provider: "youtube",
      providerItemId: videoId,
      status: "pending",
      sourceAttachmentsStatus: "pending",
      manualOverride: existing?.manualOverride ?? false,
      sourceTranscript: existing?.sourceTranscript ?? null,
      text: existing?.text ?? null,
      revision: existing?.revision ?? 0,
    })
    .onConflictDoUpdate({
      target: [bookmarkTranscripts.bookmarkId, bookmarkTranscripts.provider],
      set: {
        providerItemId: videoId,
        status: "pending",
        statusMessage: null,
        sourceAttachmentsStatus: "pending",
      },
    });

  const user = await db.query.users.findFirst({
    where: eq(users.id, bookmark.userId),
    columns: { inferredTagLang: true, autoSummarizationEnabled: true },
  });
  const shouldSummarize =
    serverConfig.inference.enableAutoSummarization &&
    user?.autoSummarizationEnabled !== false;

  let artifacts: CaptionArtifact[];
  try {
    artifacts = await downloadCaptionArtifacts(bookmark.link.url, videoId, job);
  } catch (error) {
    await db
      .update(bookmarkTranscripts)
      .set({
        providerItemId: videoId,
        status: "failed",
        statusMessage: error instanceof Error ? error.message : String(error),
        sourceAttachmentsStatus: existing?.sourceAttachmentsStatus ?? "failed",
      })
      .where(
        and(
          eq(bookmarkTranscripts.bookmarkId, bookmark.id),
          eq(bookmarkTranscripts.provider, "youtube"),
        ),
      );
    if (!job.data.forceEnrichment) {
      await clearPendingSummaryIfEmpty(bookmark);
    }
    throw error;
  }

  if (artifacts.length === 0 && serverConfig.transcription.enabled) {
    let result;
    try {
      result = await transcribeRemoteUrl(bookmark.link.url, job.abortSignal);
    } catch (error) {
      await db
        .update(bookmarkTranscripts)
        .set({
          providerItemId: videoId,
          status: "failed",
          statusMessage: error instanceof Error ? error.message : String(error),
          sourceAttachmentsStatus:
            existing?.sourceAttachmentsStatus ?? "failed",
        })
        .where(
          and(
            eq(bookmarkTranscripts.bookmarkId, bookmark.id),
            eq(bookmarkTranscripts.provider, "youtube"),
          ),
        );
      if (!job.data.forceEnrichment) {
        await clearPendingSummaryIfEmpty(bookmark);
      }
      throw error;
    }

    const sourceFingerprint = fingerprintTranscript(
      "youtube",
      videoId,
      result.text,
    );
    const saved = await saveGeneratedTranscript({
      bookmark,
      provider: "youtube",
      providerItemId: videoId,
      sourceTranscript: result.text,
      sourceLanguage: result.language,
      selectedTrackId: "azure-speech",
      sourceFingerprint,
      shouldSummarize,
    });

    if (saved.sourceChanged) {
      const oldAssetIds = await db
        .select({ id: assets.id })
        .from(assets)
        .where(
          and(
            eq(assets.bookmarkId, bookmark.id),
            eq(assets.assetType, AssetTypes.CAPTION_SOURCE),
          ),
        );
      await db
        .delete(assets)
        .where(
          and(
            eq(assets.bookmarkId, bookmark.id),
            eq(assets.assetType, AssetTypes.CAPTION_SOURCE),
          ),
        );
      await deleteOldCaptionAssets(
        bookmark.userId,
        oldAssetIds.map((asset) => asset.id),
      );
    }

    if (
      (saved.sourceChanged && !saved.manualOverride) ||
      job.data.forceEnrichment
    ) {
      await enqueueTranscriptEnrichment(bookmark, job);
      if (shouldSummarize) {
        await enqueueTranscriptSummary(bookmark, job, saved.nextRevision);
      }
    }
    await SearchIndexingQueue.enqueue(
      { bookmarkId: bookmark.id, type: "index" },
      {
        priority: job.priority ?? QueuePriority.Default,
        groupId: bookmark.userId,
      },
    );
    addLogFields<"transcriptWorker.run">({
      "bookmark.id": bookmark.id,
      "transcript.provider": "youtube",
      "transcript.source_language": result.language,
      "transcript.source_files": 0,
    });
    return;
  }

  if (artifacts.length === 0) {
    await db
      .update(bookmarkTranscripts)
      .set({
        providerItemId: videoId,
        status: "unavailable",
        statusMessage: serverConfig.transcription.enabled
          ? "No usable YouTube captions or transcription were found"
          : "No usable YouTube captions were found and audio transcription is disabled",
        sourceAttachmentsStatus: existing?.sourceAttachmentsStatus ?? "ready",
      })
      .where(
        and(
          eq(bookmarkTranscripts.bookmarkId, bookmark.id),
          eq(bookmarkTranscripts.provider, "youtube"),
        ),
      );
    if (job.data.forceEnrichment) {
      await enqueueRefreshFallbackEnrichment(
        bookmark,
        job.id,
        job.priority,
        bookmark.summarizationStatus === "pending",
      );
    } else {
      await clearPendingSummaryIfEmpty(bookmark);
    }
    return;
  }

  const selected = selectCaptionArtifact(
    artifacts,
    user?.inferredTagLang ?? serverConfig.inference.inferredTagLang,
  );
  const selectedText = normalizeSubtitleText(selected.bytes.toString("utf8"));
  if (!selectedText) {
    await db
      .update(bookmarkTranscripts)
      .set({
        providerItemId: videoId,
        status: "unavailable",
        statusMessage:
          "Selected YouTube caption track contained no readable text",
        sourceAttachmentsStatus: existing?.sourceAttachmentsStatus ?? "ready",
      })
      .where(
        and(
          eq(bookmarkTranscripts.bookmarkId, bookmark.id),
          eq(bookmarkTranscripts.provider, "youtube"),
        ),
      );
    if (job.data.forceEnrichment) {
      await enqueueRefreshFallbackEnrichment(
        bookmark,
        job.id,
        job.priority,
        bookmark.summarizationStatus === "pending",
      );
    } else {
      await clearPendingSummaryIfEmpty(bookmark);
    }
    return;
  }

  const sourceFingerprint = fingerprintArtifact(selected);
  const sourceChanged = existing?.sourceFingerprint !== sourceFingerprint;
  const manualOverride = existing?.manualOverride ?? false;
  const nextRevision = sourceChanged
    ? (existing?.revision ?? 0) + (manualOverride ? 0 : 1)
    : (existing?.revision ?? 0);
  const savedArtifacts: { artifact: CaptionArtifact; assetId: string }[] = [];
  const failedAttachmentCount = { value: 0 };

  for (const artifact of artifacts) {
    const assetId = newAssetId();
    const artifactPath = path.join(
      os.tmpdir(),
      `marka-caption-${assetId}-${artifact.fileName}`,
    );
    await fs.promises.writeFile(artifactPath, artifact.bytes);
    try {
      const quotaApproved = await QuotaService.checkStorageQuota(
        db,
        bookmark.userId,
        artifact.bytes.length,
      );
      await saveAssetFromFile({
        userId: bookmark.userId,
        assetId,
        assetPath: artifactPath,
        metadata: {
          contentType: artifact.contentType,
          fileName: artifact.fileName,
        },
        quotaApproved,
      });
      savedArtifacts.push({ artifact, assetId });
    } catch (error) {
      failedAttachmentCount.value += 1;
      await silentDeleteAsset(bookmark.userId, assetId);
      await fs.promises
        .rm(artifactPath, { force: true })
        .catch(() => undefined);
      logger.warn(
        `[transcript][${job.id}] Failed to preserve caption source ${artifact.fileName}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  const sourceAttachmentsStatus =
    savedArtifacts.length === artifacts.length
      ? "ready"
      : savedArtifacts.length > 0
        ? "partial"
        : "failed";

  const oldAssetIds = await db
    .select({ id: assets.id })
    .from(assets)
    .where(
      and(
        eq(assets.bookmarkId, bookmark.id),
        eq(assets.assetType, AssetTypes.CAPTION_SOURCE),
      ),
    );

  await db.transaction(async (tx) => {
    const transcript = await tx.query.bookmarkTranscripts.findFirst({
      where: and(
        eq(bookmarkTranscripts.bookmarkId, bookmark.id),
        eq(bookmarkTranscripts.provider, "youtube"),
      ),
    });
    if (!transcript) {
      throw new Error("Transcript row disappeared during processing");
    }

    if (savedArtifacts.length > 0) {
      await tx
        .delete(assets)
        .where(
          and(
            eq(assets.bookmarkId, bookmark.id),
            eq(assets.assetType, AssetTypes.CAPTION_SOURCE),
          ),
        );
      await tx.insert(assets).values(
        savedArtifacts.map(({ artifact, assetId }) => ({
          id: assetId,
          assetType: AssetTypes.CAPTION_SOURCE,
          size: artifact.bytes.length,
          contentType: artifact.contentType,
          fileName: artifact.fileName,
          bookmarkId: bookmark.id,
          transcriptId: transcript.id,
          userId: bookmark.userId,
        })),
      );
    }

    await tx
      .update(bookmarkTranscripts)
      .set({
        providerItemId: videoId,
        status: "ready",
        statusMessage:
          failedAttachmentCount.value > 0
            ? `${failedAttachmentCount.value} caption source attachment(s) could not be preserved`
            : null,
        sourceAttachmentsStatus,
        selectedTrackId: selected.fileName,
        sourceLanguage: selected.language,
        sourceIsAutoGenerated: selected.isAutoGenerated,
        sourceTranscript: selectedText,
        text: manualOverride ? transcript.text : selectedText,
        manualOverride,
        revision: nextRevision,
        sourceFingerprint,
        sourceFetchedAt: new Date(),
        modifiedAt: new Date(),
      })
      .where(eq(bookmarkTranscripts.id, transcript.id));

    if (sourceChanged && !manualOverride) {
      const bookmarkRow = await tx.query.bookmarks.findFirst({
        where: eq(bookmarks.id, bookmark.id),
        columns: { summaryProvenance: true },
      });
      if (bookmarkRow?.summaryProvenance !== "manual") {
        await tx
          .update(bookmarks)
          .set({
            summaryProvenance: "transcript",
            summaryStale: true,
            summarizationStatus: shouldSummarize ? "pending" : null,
            modifiedAt: new Date(),
          })
          .where(eq(bookmarks.id, bookmark.id));
      }
    }
  });

  if (savedArtifacts.length > 0) {
    await deleteOldCaptionAssets(
      bookmark.userId,
      oldAssetIds.map((asset) => asset.id),
    );
  }

  const enqueueOpts: EnqueueOptions = {
    priority: job.priority ?? QueuePriority.Default,
    groupId: bookmark.userId,
  };
  if ((sourceChanged && !manualOverride) || job.data.forceEnrichment) {
    await enqueueTranscriptEnrichment(bookmark, job);
    if (shouldSummarize) {
      await enqueueTranscriptSummary(bookmark, job, nextRevision);
    }
  }
  await SearchIndexingQueue.enqueue(
    { bookmarkId: bookmark.id, type: "index" },
    enqueueOpts,
  );

  addLogFields<"transcriptWorker.run">({
    "bookmark.id": bookmark.id,
    "transcript.provider": "youtube",
    "transcript.source_language": selected.language ?? undefined,
    "transcript.source_files": artifacts.length,
  });
}

export class TranscriptWorker {
  static async build() {
    logger.info("Starting transcript worker ...");
    return (await getQueueClient())!.createRunner<ZTranscriptRequest>(
      TranscriptQueue,
      {
        run: withWorkerTracing(
          "transcriptWorker.run",
          withWorkerEventLog("transcriptWorker.run", runWorker),
        ),
        onComplete: () => {
          workerStatsCounter.labels("transcript", "completed").inc();
          return Promise.resolve();
        },
        onError: async (job) => {
          workerStatsCounter.labels("transcript", "failed").inc();
          if (job.numRetriesLeft === 0) {
            workerStatsCounter.labels("transcript", "failed_permanent").inc();
            if (job.data?.forceEnrichment) {
              const bookmarkId = job.data.bookmarkId;
              const bookmark = await db.query.bookmarks.findFirst({
                where: eq(bookmarks.id, bookmarkId),
                columns: {
                  id: true,
                  userId: true,
                  summarizationStatus: true,
                },
              });
              let fallbackQueued = false;
              if (bookmark) {
                try {
                  await enqueueRefreshFallbackEnrichment(
                    bookmark,
                    job.id,
                    job.priority,
                    bookmark.summarizationStatus === "pending",
                  );
                  fallbackQueued = true;
                } catch (error) {
                  logger.error(
                    `[transcript][${job.id}] Failed to enqueue refresh fallback enrichment: ${error instanceof Error ? error.message : String(error)}`,
                  );
                }
              }
              if (!fallbackQueued) {
                await db.transaction(async (tx) => {
                  await tx
                    .update(bookmarks)
                    .set({ taggingStatus: null })
                    .where(
                      and(
                        eq(bookmarks.id, bookmarkId),
                        eq(bookmarks.taggingStatus, "pending"),
                      ),
                    );
                  await tx
                    .update(bookmarks)
                    .set({ summarizationStatus: null })
                    .where(
                      and(
                        eq(bookmarks.id, bookmarkId),
                        eq(bookmarks.summarizationStatus, "pending"),
                      ),
                    );
                  await tx
                    .update(bookmarks)
                    .set({ embeddingStatus: null })
                    .where(
                      and(
                        eq(bookmarks.id, bookmarkId),
                        eq(bookmarks.embeddingStatus, "pending"),
                      ),
                    );
                });
              }
            }
          }
        },
      },
      {
        concurrency: 1,
        pollIntervalMs: 1000,
        timeoutSecs: Math.max(
          serverConfig.crawler.downloadVideoTimeout,
          serverConfig.transcription.jobTimeoutSec,
        ),
        validator: zTranscriptRequestSchema,
      },
    );
  }
}

async function runWorker(job: DequeuedJob<ZTranscriptRequest>) {
  try {
    await runTranscript(job);
  } catch (error) {
    logger.error(
      `[transcript][${job.id}] Transcript ingestion failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    throw error;
  }
}
